services:
  - type: web
    name: my-fast-downloader
    env: python
    buildCommand: pip install -r requirements.txt && apt-get update && apt-get install -y ffmpeg
    startCommand: gunicorn app:app
    plan: free
    region: singapore
